/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{astro,html,jsx,md,mdx,svelte,ts,tsx,vue}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },

    extend: {
      fontFamily: {
        body: [
          'Wotfard',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Oxygen',
          'Ubuntu',
          'Cantarell',
          'Fira Sans',
          'Droid Sans',
          'Helvetica Neue',
          'sans-serif',
        ],
        heading: [
          'AcidGrotesk',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Oxygen',
          'Ubuntu',
          'Cantarell',
          'Fira Sans',
          'Droid Sans',
          'Helvetica Neue',
          'sans-serif',
        ],
        code: ['MonoLisa', 'monaco', 'Consolas', 'Lucida Console', 'monospace'],
      },
      colors: {
        amber: {
          50: 'hsl(var(--amber-50))',
          100: 'hsl(var(--amber-100))',
          200: 'hsl(var(--amber-200))',
          300: 'hsl(var(--amber-300))',
          400: 'hsl(var(--amber-400))',
          500: 'hsl(var(--amber-500))',
          600: 'hsl(var(--amber-600))',
          700: 'hsl(var(--amber-700))',
          800: 'hsl(var(--amber-800))',
          900: 'hsl(var(--amber-900))',
          950: 'hsl(var(--amber-950))',
        },
        blue: {
          50: 'hsl(var(--blue-50))',
          100: 'hsl(var(--blue-100))',
          200: 'hsl(var(--blue-200))',
          300: 'hsl(var(--blue-300))',
          400: 'hsl(var(--blue-400))',
          500: 'hsl(var(--blue-500))',
          600: 'hsl(var(--blue-600))',
          700: 'hsl(var(--blue-700))',
          800: 'hsl(var(--blue-800))',
          900: 'hsl(var(--blue-900))',
          950: 'hsl(var(--blue-950))',
        },
        core: {
          black: 'hsl(var(--core-black))',
          white: 'hsl(var(--core-white))',
        },
        green: {
          50: 'hsl(var(--green-50))',
          100: 'hsl(var(--green-100))',
          200: 'hsl(var(--green-200))',
          300: 'hsl(var(--green-300))',
          400: 'hsl(var(--green-400))',
          500: 'hsl(var(--green-500))',
          600: 'hsl(var(--green-600))',
          700: 'hsl(var(--green-700))',
          800: 'hsl(var(--green-800))',
          900: 'hsl(var(--green-900))',
          950: 'hsl(var(--green-950))',
        },

        neutral: {
          25: 'hsl(var(--neutral-25))',
          50: 'hsl(var(--neutral-50))',
          100: 'hsl(var(--neutral-100))',
          150: 'hsl(var(--neutral-150))',
          200: 'hsl(var(--neutral-200))',
          250: 'hsl(var(--neutral-250))',
          300: 'hsl(var(--neutral-300))',
          350: 'hsl(var(--neutral-350))',
          400: 'hsl(var(--neutral-400))',
          450: 'hsl(var(--neutral-450))',
          500: 'hsl(var(--neutral-500))',
          550: 'hsl(var(--neutral-550))',
          600: 'hsl(var(--neutral-600))',
          650: 'hsl(var(--neutral-650))',
          700: 'hsl(var(--neutral-700))',
          750: 'hsl(var(--neutral-750))',
          800: 'hsl(var(--neutral-800))',
          850: 'hsl(var(--neutral-850))',
          900: 'hsl(var(--neutral-900))',
          950: 'var(var(--neutral-950))',
        },

        neutral2: {
          25: 'hsl(var(--neutral2-25))',
          50: 'hsl(var(--neutral2-50))',
          100: 'hsl(var(--neutral2-100))',
          150: 'hsl(var(--neutral2-150))',
          200: 'hsl(var(--neutral2-200))',
          250: 'hsl(var(--neutral2-250))',
          300: 'hsl(var(--neutral2-300))',
          350: 'hsl(var(--neutral2-350))',
          400: 'hsl(var(--neutral2-400))',
          450: 'hsl(var(--neutral2-450))',
          500: 'hsl(var(--neutral2-500))',
          550: 'hsl(var(--neutral2-550))',
          600: 'hsl(var(--neutral2-600))',
          650: 'hsl(var(--neutral2-650))',
          700: 'hsl(var(--neutral2-700))',
          750: 'hsl(var(--neutral2-750))',
          800: 'hsl(var(--neutral2-800))',
          850: 'hsl(var(--neutral2-850))',
          900: 'hsl(var(--neutral2-900))',
          950: 'hsl(var(--neutral2-950))',
        },

        purple: {
          50: 'hsl(var(--purple-50))',
          100: 'hsl(var(--purple-100))',
          200: 'hsl(var(--purple-200))',
          300: 'hsl(var(--purple-300))',
          400: 'hsl(var(--purple-400))',
          500: 'hsl(var(--purple-500))',
          600: 'hsl(var(--purple-600))',
          700: 'hsl(var(--purple-700))',
          800: 'hsl(var(--purple-800))',
          900: 'hsl(var(--purple-900))',
          950: 'hsl(var(--purple-950))',
        },

        red: {
          50: 'hsl(var(--red-50))',
          100: 'hsl(var(--red-100))',
          200: 'hsl(var(--red-200))',
          300: 'hsl(var(--red-300))',
          400: 'hsl(var(--red-400))',
          500: 'hsl(var(--red-500))',
          600: 'hsl(var(--red-600))',
          700: 'hsl(var(--red-700))',
          800: 'hsl(var(--red-800))',
          900: 'hsl(var(--red-900))',
          950: 'hsl(var(--red-950))',
        },

        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      strokeWidth: {
        1.5: '1.5',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
